keys:
  - &users
    - &ta age1702g76a5wpqw0yz0et0kqp7qz4tsph7rurrklmp0e5z6dnmugdsqhgasy0
  - &hosts:
    - &gtx-nix: age1hptu7pzhfpxvtkk5duyeyan3fptuqucs52p4ylvdtfc3y757e9ssp0v5qd
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *ta
        - *gtx-nix

